site_name: {{cookiecutter.appData.appName.replace('-','_'}}
site_description: Documentation for {{cookiecutter.appData.appName.replace('-','_'}}
docs_dir: 'docs'
site_dir: 'site'
theme:
  name: material
markdown_extensions:
  - toc:
      permalink: "#"
nav:
  - Home: 'index.md'
